---
title: Obres i Serveis Carmelo
timezone: Europe/Madrid
collections:
  clientes:
    title: Clientes
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: projectes
    title_1: lol
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
theme: jekyll-theme-cayman
