---
title: Obres i Serveis Carmelo
timezone: Europe/Madrid
permalink: pretty
collections:
  projectes:
    output: true
    permalink: /:collection/:name
  serveis:
    output: true
    permalink: /:collection/:name
